globalThis.process ??= {}; globalThis.process.env ??= {};
/* empty css                                 */
import { c as createAstro, a as createComponent, r as renderTemplate, m as maybeRenderHead, b as addAttribute, e as renderSlot, d as renderComponent, F as Fragment } from '../chunks/astro/server_CdBmRXS2.mjs';
/* empty css                                 */
import { $ as $$Layout } from '../chunks/Layout_ezAuWzDd.mjs';
import { $ as $$Icon, a as $$Colors } from '../chunks/Icon_Bm4M-HLU.mjs';
import { $ as $$PriceSection } from '../chunks/price_section_o2ITpXWH.mjs';
export { renderers } from '../renderers.mjs';

/** @returns {void} */

function run(fn) {
	return fn();
}

function blank_object() {
	return Object.create(null);
}

/**
 * @param {Function[]} fns
 * @returns {void}
 */
function run_all(fns) {
	fns.forEach(run);
}

let current_component;

/** @returns {void} */
function set_current_component(component) {
	current_component = component;
}

// general each functions:

function ensure_array_like(array_like_or_iterator) {
	return array_like_or_iterator?.length !== undefined
		? array_like_or_iterator
		: Array.from(array_like_or_iterator);
}

const ATTR_REGEX = /[&"]/g;
const CONTENT_REGEX = /[&<]/g;

/**
 * Note: this method is performance sensitive and has been optimized
 * https://github.com/sveltejs/svelte/pull/5701
 * @param {unknown} value
 * @returns {string}
 */
function escape(value, is_attr = false) {
	const str = String(value);
	const pattern = is_attr ? ATTR_REGEX : CONTENT_REGEX;
	pattern.lastIndex = 0;
	let escaped = '';
	let last = 0;
	while (pattern.test(str)) {
		const i = pattern.lastIndex - 1;
		const ch = str[i];
		escaped += str.substring(last, i) + (ch === '&' ? '&amp;' : ch === '"' ? '&quot;' : '&lt;');
		last = i + 1;
	}
	return escaped + str.substring(last);
}

/** @returns {string} */
function each(items, fn) {
	items = ensure_array_like(items);
	let str = '';
	for (let i = 0; i < items.length; i += 1) {
		str += fn(items[i], i);
	}
	return str;
}

function validate_component(component, name) {
	if (!component || !component.$$render) {
		throw new Error(
			`<${name}> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a <${name}>.`
		);
	}
	return component;
}

let on_destroy;

/** @returns {{ render: (props?: {}, { $$slots, context }?: { $$slots?: {}; context?: Map<any, any>; }) => { html: any; css: { code: string; map: any; }; head: string; }; $$render: (result: any, props: any, bindings: any, slots: any, context: any) => any; }} */
function create_ssr_component(fn) {
	function $$render(result, props, bindings, slots, context) {
		const parent_component = current_component;
		const $$ = {
			on_destroy,
			context: new Map(context || (parent_component ? parent_component.$$.context : [])),
			// these will be immediately discarded
			on_mount: [],
			before_update: [],
			after_update: [],
			callbacks: blank_object()
		};
		set_current_component({ $$ });
		const html = fn(result, props, bindings, slots);
		set_current_component(parent_component);
		return html;
	}
	return {
		render: (props = {}, { $$slots = {}, context = new Map() } = {}) => {
			on_destroy = [];
			const result = { title: '', head: '', css: new Set() };
			const html = $$render(result, props, {}, $$slots, context);
			run_all(on_destroy);
			return {
				html,
				css: {
					code: Array.from(result.css)
						.map((css) => css.code)
						.join('\n'),
					map: null // TODO
				},
				head: result.title + result.head
			};
		},
		$$render
	};
}

/** @returns {string} */
function add_attribute(name, value, boolean) {
	if (value == null || (boolean)) return '';
	const assignment = `="${escape(value, true)}"`;
	return ` ${name}${assignment}`;
}

/* src/components/product-carousel.svelte generated by Svelte v4.2.12 */

const Product_carousel = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<div>${slots.default ? slots.default({}) : ``}</div>`;
});

const $$Astro$1 = createAstro("https://melushstore.com");
const $$ContentSection = createComponent(($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$1, $$props, $$slots);
  Astro2.self = $$ContentSection;
  const { title, id, position } = Astro2.props;
  const positionClass = position === void 0 ? "items-center" : `items-${position}`;
  return renderTemplate`${maybeRenderHead()}<section${addAttribute(id, "id")}${addAttribute(`flex scroll-mt-24 flex-col gap-4 space-y-8 ${positionClass}`, "class")}> ${title && renderTemplate`<header class="flex flex-col items-center gap-4"> ${renderSlot($$result, $$slots["eyebrow"])} <h2 class="text text-center font-extrabold tracking-tight text-6xl"> ${title} </h2> </header>` || renderTemplate`${renderComponent($$result, "Icon", $$Icon, { "class": "h-8 w-full sm:h-16", "name": "MELUSH" })}`} <p class="max-w-xl text-center font-extrabold text-2xl"> ${renderSlot($$result, $$slots["lead"])} </p> ${renderSlot($$result, $$slots["default"])} </section>`;
}, "/home/runner/work/website/website/src/components/content-section.astro", void 0);

/* src/components/image.svelte generated by Svelte v4.2.12 */

const css$1 = {
	code: "figure.svelte-1x58mk1{background:var(--grey-1);border:2px solid var(--grey-2);box-shadow:var(--box-shadow-glow);border-radius:0.5rem;margin:0;padding-bottom:1rem}figcaption.svelte-1x58mk1{padding-inline:1rem}.media.svelte-1x58mk1{width:100%;height:auto;aspect-ratio:10 / 10;-o-object-fit:cover;object-fit:cover;border-radius:inherit;border:none}",
	map: null
};

const Image = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { src = '' } = $$props;
	let { alt = '' } = $$props;
	if ($$props.src === void 0 && $$bindings.src && src !== void 0) $$bindings.src(src);
	if ($$props.alt === void 0 && $$bindings.alt && alt !== void 0) $$bindings.alt(alt);
	$$result.css.add(css$1);
	return `   <figure class="svelte-1x58mk1"><img class="media svelte-1x58mk1"${add_attribute("src", src, 0)}${add_attribute("alt", alt, 0)}> <figcaption class="svelte-1x58mk1"> ${slots.figcaption ? slots.figcaption({}) : ``}</figcaption> </figure>`;
});

/* src/components/carousel.svelte generated by Svelte v4.2.12 */

const css = {
	code: ".image-container.svelte-uykhpv.svelte-uykhpv{grid-area:1 / -1}button.svelte-uykhpv.svelte-uykhpv{background:none;border:none;color:var(--color-text-secondary);border-radius:0.3rem;transition:background-color 0.2s;display:flex;justify-content:center;align-items:center}button.svelte-uykhpv.svelte-uykhpv:hover,button.svelte-uykhpv.svelte-uykhpv:focus-visible{background-color:var(--grey-2)}button.svelte-uykhpv svg.svelte-uykhpv{width:100%;height:auto}",
	map: null
};

const Carousel = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { images = [] } = $$props;
	let currentIdx = 0;

	if ($$props.images === void 0 && $$bindings.images && images !== void 0) $$bindings.images(images);
	$$result.css.add(css);

	return `<div class="grid w-full">${each(images, (image, idx) => {
		return `${idx === currentIdx
		? `<div class="image-container relative svelte-uykhpv">${validate_component(Image, "Image").$$render(
				$$result,
				{
					class: "absolute top-0 left-0 w-full h-full object-cover",
					title: image.id,
					src: image.url,
					alt: // TODO: image.alt
					// image.explanation
					'Clothes from melush'
				},
				{},
				{
					figcaption: () => {
						return `<div slot="figcaption" class="absolute bottom-0 top-0 left-0 flex justify-between w-full">${images.length > 1
						? `<button aria-label="Previous" class="svelte-uykhpv" data-svelte-h="svelte-1oywjcz"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--material-symbols svelte-uykhpv" width="32" height="32" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><title>Previous</title><path fill="currentColor" d="m12.3 15.3l-2.6-2.6q-.15-.15-.225-.325Q9.4 12.2 9.4 12t.075-.375q.075-.175.225-.325l2.6-2.6q.475-.475 1.087-.212q.613.262.613.937v5.15q0 .675-.613.937q-.612.263-1.087-.212Z"></path></svg></button> <button aria-label="Next" class="svelte-uykhpv" data-svelte-h="svelte-102e52i"> <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--material-symbols svelte-uykhpv" width="32" height="32" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><title>Next</title><path fill="currentColor" d="M11.7 15.3q-.475.475-1.087.212Q10 15.25 10 14.575v-5.15q0-.675.613-.937q.612-.263 1.087.212l2.6 2.6q.15.15.225.325q.075.175.075.375t-.075.375q-.075.175-.225.325Z"></path></svg> </button>`
						: ``} </div>`;
					}
				}
			)} </div>`
		: ``}`;
	})} </div>`;
});

const $$Catalogue = createComponent(async ($$result, $$props, $$slots) => {
  const bannedItems = ["984371e5-2aee-4884-84a0-4d92ae761b8e"];
  const clothes = await fetch("https://api.melushstore.com/store_public").then((res) => res.json()).then((data) => data).then((data) => data.filter(({ imagesUrl }) => imagesUrl.length > 0)).then((data) => data.filter(({ id }) => !bannedItems.includes(id)));
  return renderTemplate`${renderComponent($$result, "ContentSection", $$ContentSection, { "id": "catalogue" }, { "default": ($$result2) => renderTemplate` ${renderComponent($$result2, "ProductCarousel", Product_carousel, { "client:idle": true, "client:component-hydration": "idle", "client:component-path": "~/components/product-carousel.svelte", "client:component-export": "default" }, { "default": ($$result3) => renderTemplate` ${maybeRenderHead()}<ul class="grid max-w-7xl grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4"> ${clothes == null ? renderTemplate`<li>Loading...</li>` : clothes.map(({ id, title, materials, sizes, price, discount, imagesUrl, colors }) => renderTemplate`<li> <a class="flex flex-col items-start gap-4 rounded-lg border border-default bg-offset p-2"${addAttribute(`/item/${id}`, "href")}> ${imagesUrl && renderTemplate`${renderComponent($$result3, "Carousel", Carousel, { "client:load": true, "images": imagesUrl, "client:component-hydration": "load", "client:component-path": "/home/runner/work/website/website/src/components/carousel.svelte", "client:component-export": "default" })}`} <header class="text-center font-extrabold text-xl">${title}</header> ${renderComponent($$result3, "Colors", $$Colors, { "colors": colors })} <section class="flex w-full justify-between space-x-4"> <p class="text text-base">Materiales</p> <p class="truncate font-semibold text-offset text-base"> ${materials.map(({ name }) => name).join(", ")} </p> </section> <section class="flex w-full justify-between"> <p class="text text-base">Tallas</p> <p class="font-semibold text-offset text-base"> ${sizes.map(({ name }) => name).join(", ")} </p> </section> ${renderComponent($$result3, "PriceC", $$PriceSection, { "price": price, "discount": discount })} </a> </li>`)} </ul> ` })} ` })}`;
}, "/home/runner/work/website/website/src/components/catalogue.astro", void 0);

const $$Astro = createAstro("https://melushstore.com");
const $$ContactInfo = createComponent(($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$ContactInfo;
  const { items } = Astro2.props;
  return renderTemplate`${maybeRenderHead()}<article class="max-w-6xl space-y-2"> <ul class="px-6 pb-4 pt-8 sm:grid-cols-3 md:grid-cols-6"> ${items.map((item) => renderTemplate`<li> <a class="flex items-center gap-2"${addAttribute(item.url, "href")}> ${renderComponent($$result, "Icon", $$Icon, { "class": "h-8", "name": item.icon })} <span class="p-2 font-mono text-xl">${item.title}</span> </a> </li>`)} </ul> </article>`;
}, "/home/runner/work/website/website/src/components/contact-info.astro", void 0);

const $$Contact = createComponent(($$result, $$props, $$slots) => {
  const contactPlatforms = [
    {
      title: "(+51) 982 391 450",
      icon: "mdi:whatsapp",
      url: "https://wa.me/+51982391450"
    }
  ];
  return renderTemplate`${renderComponent($$result, "ContentSection", $$ContentSection, { "id": "contact", "title": "Hecho con amor \u{1F496}" }, { "default": ($$result2) => renderTemplate`  ${renderComponent($$result2, "ContactInfo", $$ContactInfo, { "items": contactPlatforms })} `, "lead": ($$result2) => renderTemplate`${renderComponent($$result2, "Fragment", Fragment, { "slot": "lead" }, { "default": ($$result3) => renderTemplate`
Nos destacamos por ofrecer prendas con buena ${maybeRenderHead()}<span class="text-offset">
calidad y acabados</span>
pensando en la <span class="text-offset">comodidad</span> de nuestros
        clientes.
` })}` })}`;
}, "/home/runner/work/website/website/src/components/contact.astro", void 0);

const $$Index = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${renderComponent($$result, "Layout", $$Layout, {}, { "default": ($$result2) => renderTemplate`  ${maybeRenderHead()}<main class="space-y-24 px-4 pb-32 pt-16 lg:px-0"> ${renderComponent($$result2, "Catalogue", $$Catalogue, {})} ${renderComponent($$result2, "Contact", $$Contact, {})} </main> ` })}`;
}, "/home/runner/work/website/website/src/pages/index.astro", void 0);

const $$file = "/home/runner/work/website/website/src/pages/index.astro";
const $$url = "";

const _page = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
	__proto__: null,
	default: $$Index,
	file: $$file,
	url: $$url
}, Symbol.toStringTag, { value: 'Module' }));

const page = () => _page;

export { page };
